# Inventário dos cursos

In [18]:
import pandas as pd
from pathlib import Path

pd.set_option("display.max_rows", 500)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [ ]:
from pathlib import Path


def resolver_base() -> Path:
    """Resolve o diretório raiz do projeto em qualquer ambiente."""
    cwd = Path.cwd().resolve()

    for candidate in [cwd, *cwd.parents]:
        if (candidate / "tsv").exists() and (candidate / "catalogos").exists():
            return candidate

    return cwd


BASE = resolver_base()

DIR_TSV = BASE / "tsv"
DIR_CATALOGOS = BASE / "catalogos"
DIR_RELATORIOS = BASE / "relatorios"

DIR_CATALOGOS.mkdir(parents=True, exist_ok=True)
DIR_RELATORIOS.mkdir(parents=True, exist_ok=True)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [20]:
TRIENIOS = [
    "2018-2020",
    "2019-2021",
    "2020-2022",
    "2021-2023",
    "2022-2024",
    "2023-2025",
]

ARQUIVOS = {
    trienio: DIR_TSV / f"{trienio}.tsv"
    for trienio in TRIENIOS
}

In [21]:
def carregar_tsv(arquivo):
    """
    Lê um TSV do PAS detectando automaticamente
    a linha do cabeçalho.
    """

    bruto = pd.read_csv(
        arquivo,
        sep="\t",
        header=None,
        dtype=str,
        keep_default_na=False,
    )

    linha = None

    for i, valores in bruto.iterrows():

        valores = (
            valores.fillna("")
                   .astype(str)
                   .str.strip()
                   .tolist()
        )

        if {"Curso", "Turno"}.issubset(valores):
            linha = i
            break

    if linha is None:
        raise ValueError(
            f"Cabeçalho não encontrado em {arquivo.name}"
        )

    df = pd.read_csv(
        arquivo,
        sep="\t",
        header=linha,
        dtype=str,
        keep_default_na=False,
    )

    df.columns = (
        pd.Index(df.columns)
        .astype(str)
        .str.strip()
    )

    return df


def carregar_dados(arquivos):
    """
    Carrega todos os TSVs do projeto.
    """

    dados = {}

    print("=" * 70)
    print("CARREGANDO TSVs")
    print("=" * 70)

    for trienio, arquivo in arquivos.items():

        if not arquivo.exists():
            raise FileNotFoundError(arquivo)

        df = carregar_tsv(arquivo)

        obrigatorias = {"Curso", "Turno"}

        faltantes = obrigatorias - set(df.columns)

        if faltantes:
            raise ValueError(
                f"{arquivo.name}: colunas ausentes {sorted(faltantes)}"
            )

        dados[trienio] = df

        print(
            f"✓ {trienio:<10}"
            f" {len(df):>4} linhas"
            f" | {len(df.columns):>2} colunas"
        )

    return dados

In [22]:
DADOS = carregar_dados(ARQUIVOS)

======================================================================
CARREGANDO TSVs
======================================================================
✓ 2018-2020   109 linhas | 22 colunas
✓ 2019-2021   100 linhas | 23 colunas
✓ 2020-2022   106 linhas | 22 colunas
✓ 2021-2023   105 linhas | 22 colunas
✓ 2022-2024    60 linhas | 22 colunas
✓ 2023-2025   103 linhas | 22 colunas

# Normalização do Inventário

In [23]:
# ============================================================
# HISTÓRICO DOS CURSOS
# ============================================================

historico = []

for trienio, df in DADOS.items():

    cursos = (
        df["Curso"]
        .fillna("")
        .astype(str)
        .str.strip()
    )

    cursos = cursos[cursos != ""]

    historico.extend(
        {
            "Triênio": trienio,
            "Curso": curso
        }
        for curso in cursos
    )

historico = pd.DataFrame(historico)

display(historico.head())

     Triênio                              Curso
0  2018-2020        Campus UnB — Ceilândia / DF
1  2018-2020  Terapia Ocupacional (Bacharelado)
2  2018-2020       Fonoaudiologia (Bacharelado)
3  2018-2020         Fisioterapia (Bacharelado)
4  2018-2020             Farmácia (Bacharelado)

In [24]:
# ============================================================
# FREQUÊNCIAS
# ============================================================

frequencias = (

    historico

    .groupby("Curso")

    .agg(

        Ocorrências=("Curso", "size"),

        Triênios=("Triênio", "nunique"),

        Lista_de_triênios=(

            "Triênio",

            lambda x: ", ".join(sorted(set(x)))

        )

    )

    .reset_index()

    .sort_values(

        [

            "Triênios",

            "Ocorrências",

            "Curso"

        ],

        ascending=[False, False, True]

    )

)

display(frequencias)

,Curso,Ocorrências,Triênios,Lista_de_triênios
60,Farmácia (Bacharelado),18,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
0,Administração (Bacharelado),12,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
2,Arquitetura e Urbanismo (Bacharelado),12,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
41,Direito (Bacharelado),12,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
46,Enfermagem (Bacharelado),12,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
122,Pedagogia (Licenciatura),11,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
27,Ciências Contábeis (Bacharelado),10,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
1,Agronomia (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
14,Biotecnologia (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
19,Ciência Política (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
20,Ciência da Computação (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
28,Ciências Econômicas (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
33,Computação (Licenciatura),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
34,Comunicação Organizacional (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
36,Comunicação Social – Audiovisual (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
48,Engenharia Civil (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
49,Engenharia Elétrica (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
53,Engenharia Mecânica (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
54,Engenharia Química (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
55,Engenharia de Computação (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
56,Engenharia de Produção (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
57,Engenharia de Redes de Comunicação (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
58,Engenharias – Aeroespacial / Automotiva / Eletrônica / Energia / Software (Bacharelados)**,6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
59,Estatística (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
64,Fisioterapia (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
65,Fonoaudiologia (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
79,Jornalismo (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
115,Medicina (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
116,Medicina Veterinária (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
120,Nutrição (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
121,Odontologia (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
125,Química (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
128,Relações Internacionais (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
133,Terapia Ocupacional (Bacharelado),6,6,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
129,Saúde Coletiva (Bacharelado),10,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
130,Serviço Social (Bacharelado),10,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
29,Ciências Naturais (Licenciatura),9,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
13,Biblioteconomia (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
15,Campus UnB — Ceilândia / DF,5,5,"2018-2020, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
16,Campus UnB — Darcy Ribeiro (Plano Piloto) / DF,5,5,"2018-2020, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
17,Campus UnB — Gama / DF,5,5,"2018-2020, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
24,Ciências Biológicas (Bacharelado),5,5,"2018-2020, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
35,Comunicação Social - Publicidade e Propaganda (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024"
47,Engenharia Ambiental (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
50,Engenharia Florestal (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
52,Engenharia Mecatrônica – Controle e Automação (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024"
63,Filosofia (Licenciatura),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
66,Física (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
68,Geofísica (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
71,Geologia (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
73,Gestão de Agronegócio (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
74,Gestão de Políticas Públicas (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
75,Gestão do Agronegócio (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
77,História (Bacharelado/Licenciatura),5,5,"2018-2020, 2020-2022, 2021-2023, 2022-2024, 2023-2025"
78,História (Licenciatura),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
87,Letras – Tradução – Inglês (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024"
109,Língua e Literatura Japonesa (Licenciatura),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
117,Museologia (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
119,Música (Licenciatura)*,5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
123,Psicologia (Bacharelado / Licenciatura / Psicólogo),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024"
127,Química Tecnológica (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
134,Turismo (Bacharelado),5,5,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025"
4,Arquivologia (Bacharelado),4,4,"2018-2020, 2020-2022, 2021-2023, 2023-2025"
10,Artes Visuais (Bacharelado)*,4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
18,Campus UnB — Planaltina / DF,4,4,"2018-2020, 2020-2022, 2021-2023, 2023-2025"
22,Ciências Ambientais (Bacharelado),4,4,"2018-2020, 2020-2022, 2021-2023, 2023-2025"
39,Design – Programação Visual/ Projeto do Produto (Bacharelado),4,4,"2018-2020, 2020-2022, 2021-2023, 2022-2024"
42,Educação Física (Bacharelado),4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
43,Educação Física (Licenciatura),4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
62,Filosofia (Bacharelado/Licenciatura),4,4,"2018-2020, 2020-2022, 2021-2023, 2023-2025"
70,Geografia (Bacharelado/Licenciatura),4,4,"2018-2020, 2020-2022, 2021-2023, 2023-2025"
84,Letras – Português do Brasil como Segunda Língua (Licenciatura),4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
85,Letras – Tradução Espanhol (Bacharelado),4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
86,Letras – Tradução – Francês (Bacharelado),4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
90,Licenciatura em Ciências Biológicas,4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
91,Licenciatura em Física,4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
92,Licenciatura em Matemática,4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
94,Licenciatura em Química,4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
96,Língua Espanhola e Literatura Espanhola e Hispano-Americana (Licenciatura),4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
97,Língua Estrangeira Aplicada – Multilinguismo e Sociedade da Informação (Bacharelado),4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
103,Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciatura),4,4,"2018-2020, 2020-2022, 2021-2023, 2022-2024"
107,Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciatura),4,4,"2018-2020, 2020-2022, 2021-2023, 2022-2024"
108,Língua Portuguesa e Respectiva Literatura (Licenciatura),4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
111,Matemática (Bacharelado/ Licenciatura),4,4,"2018-2020, 2020-2022, 2021-2023, 2022-2024"
118,Música (Bacharelado)*,4,4,"2018-2020, 2020-2022, 2021-2023, 2023-2025"
132,"Teoria, Crítica e História da Arte (Bacharelado)",4,4,"2018-2020, 2019-2021, 2020-2022, 2021-2023"
89,Licenciatura em Artes Cênicas*,5,3,"2018-2020, 2019-2021, 2020-2022"
8,Artes Cênicas - Interpretação Teatral (Bacharelado) *,3,3,"2018-2020, 2019-2021, 2020-2022"
30,Ciências Sociais – Antropologia / Sociologia (Bacharelado/ Licenciatura),3,3,"2018-2020, 2020-2022, 2021-2023"
72,Gestão Ambiental (Bacharelado),3,3,"2018-2020, 2019-2021, 2020-2022"
100,Língua Francesa e Respectiva Literatura (Bacharelado/Licenciatura),3,3,"2018-2020, 2020-2022, 2021-2023"
11,Artes Visuais (Licenciatura)*,3,2,"2018-2020, 2020-2022"
7,Artes Cênicas - Interpretação Teatral (Bacharelado),2,2,"2021-2023, 2022-2024"
9,Artes Visuais (Bacharelado),2,2,"2022-2024, 2023-2025"
93,Licenciatura em Música*,2,2,"2018-2020, 2019-2021"
6,Artes Cênicas (Licenciatura),2,1,2023-2025
88,Licenciatura em Artes Cênicas,2,1,2021-2023
3,Arquivologia,1,1,2019-2021
5,Artes Cênicas (Bacharelado),1,1,2023-2025
12,Artes Visuais Licenciatura,1,1,2022-2024
21,Ciências Ambientais,1,1,2019-2021
23,Ciências Biológicas,1,1,2019-2021
25,Ciências Biológicas (Licenciatura),1,1,2023-2025
26,Ciências Contábeis,1,1,2019-2021
31,Ciências Sociais – Antropologia / Sociologia (Bacharelado/Licenciat ura),1,1,2019-2021
32,Ciências Sociais – Antropologia/ Sociologia (Bacharelado/Licenciatura),1,1,2023-2025
37,Comunicação Social – Publicidade e Propaganda (Bacharelado),1,1,2023-2025
38,Design (Bacharelado),1,1,2023-2025
40,Design – Programação Visual/Projeto do Produto (Bacharelado),1,1,2019-2021
44,Educação Física Ciclo Básico,1,1,2022-2024
45,Educação Física Ciclo Básico (Bacharelado/Licenciatura),1,1,2023-2025
51,Engenharia Mecatrônica (Bacharelado),1,1,2023-2025
61,Filosofia (Bacharelado/Licenciat ura),1,1,2019-2021
67,Física (Licenciatura),1,1,2023-2025
69,Geografia (Bacharelado/Licenciat ura),1,1,2019-2021
76,História (Bacharelado/Licenciat ura),1,1,2019-2021
80,Letras Português do Brasil como Seg. Língua (Licenciatura),1,1,2023-2025
81,Letras Tradução Espanhol (Bacharelado),1,1,2023-2025
82,Letras Tradução Francês (Bacharelado),1,1,2023-2025
83,Letras Tradução Inglês (Bacharelado),1,1,2023-2025
95,Língua Espanhola e Literatura Espanhola e Hispano - Americana (Licenciatura),1,1,2023-2025
98,Língua Francesa (Bacharelado/ Licenciatura),1,1,2023-2025
99,Língua Francesa e Respectiva Literatura (Bacharelado/Licenciat ura),1,1,2019-2021
101,Língua Inglesa (Bacharelado/ Licenciatura),1,1,2023-2025
102,Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciat ura),1,1,2019-2021
104,Língua Portuguesa (Bacharelado/ Licenciatura),1,1,2023-2025
105,Língua Portuguesa (Licenciatura),1,1,2023-2025
106,Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciat ura),1,1,2019-2021
110,Línguas Estrangeiras Aplicadas (Bacharelado),1,1,2023-2025
112,Matemática (Bacharelado/Licenciat ura),1,1,2019-2021
113,Matemática (Bacharelado/Licenciatura),1,1,2023-2025
114,Matemática (Licenciatura),1,1,2023-2025
124,Psicologia (Bacharelado/Licenciatura/ Psicólogo),1,1,2023-2025
126,Química (Licenciatura),1,1,2023-2025
131,Teoria Crítica e História da Arte (Bacharelado),1,1,2023-2025

In [25]:
# ============================================================
# MATRIZ HISTÓRICA
# ============================================================

matriz = (

    historico

    .assign(Presente=1)

    .pivot_table(

        index="Curso",

        columns="Triênio",

        values="Presente",

        aggfunc="max",

        fill_value=0

    )

    .astype(int)

)

display(matriz)

Triênio,2018-2020,2019-2021,2020-2022,2021-2023,2022-2024,2023-2025
Curso,,,,,,
Administração (Bacharelado),1,1,1,1,1,1
Agronomia (Bacharelado),1,1,1,1,1,1
Arquitetura e Urbanismo (Bacharelado),1,1,1,1,1,1
Arquivologia,0,1,0,0,0,0
Arquivologia (Bacharelado),1,0,1,1,0,1
Artes Cênicas (Bacharelado),0,0,0,0,0,1
Artes Cênicas (Licenciatura),0,0,0,0,0,1
Artes Cênicas - Interpretação Teatral (Bacharelado),0,0,0,1,1,0
Artes Cênicas - Interpretação Teatral (Bacharelado) *,1,1,1,0,0,0
Artes Visuais (Bacharelado),0,0,0,0,1,1
Artes Visuais (Bacharelado)*,1,1,1,1,0,0
Artes Visuais (Licenciatura)*,1,0,1,0,0,0
Artes Visuais Licenciatura,0,0,0,0,1,0
Biblioteconomia (Bacharelado),1,1,1,1,0,1
Biotecnologia (Bacharelado),1,1,1,1,1,1
Campus UnB — Ceilândia / DF,1,0,1,1,1,1
Campus UnB — Darcy Ribeiro (Plano Piloto) / DF,1,0,1,1,1,1
Campus UnB — Gama / DF,1,0,1,1,1,1
Campus UnB — Planaltina / DF,1,0,1,1,0,1
Ciência Política (Bacharelado),1,1,1,1,1,1
Ciência da Computação (Bacharelado),1,1,1,1,1,1
Ciências Ambientais,0,1,0,0,0,0
Ciências Ambientais (Bacharelado),1,0,1,1,0,1
Ciências Biológicas,0,1,0,0,0,0
Ciências Biológicas (Bacharelado),1,0,1,1,1,1
Ciências Biológicas (Licenciatura),0,0,0,0,0,1
Ciências Contábeis,0,1,0,0,0,0
Ciências Contábeis (Bacharelado),1,1,1,1,1,1
Ciências Econômicas (Bacharelado),1,1,1,1,1,1
Ciências Naturais (Licenciatura),1,1,1,1,0,1
Ciências Sociais – Antropologia / Sociologia (Bacharelado/ Licenciatura),1,0,1,1,0,0
Ciências Sociais – Antropologia / Sociologia (Bacharelado/Licenciat ura),0,1,0,0,0,0
Ciências Sociais – Antropologia/ Sociologia (Bacharelado/Licenciatura),0,0,0,0,0,1
Computação (Licenciatura),1,1,1,1,1,1
Comunicação Organizacional (Bacharelado),1,1,1,1,1,1
Comunicação Social - Publicidade e Propaganda (Bacharelado),1,1,1,1,1,0
Comunicação Social – Audiovisual (Bacharelado),1,1,1,1,1,1
Comunicação Social – Publicidade e Propaganda (Bacharelado),0,0,0,0,0,1
Design (Bacharelado),0,0,0,0,0,1
Design – Programação Visual/ Projeto do Produto (Bacharelado),1,0,1,1,1,0
Design – Programação Visual/Projeto do Produto (Bacharelado),0,1,0,0,0,0
Direito (Bacharelado),1,1,1,1,1,1
Educação Física (Bacharelado),1,1,1,1,0,0
Educação Física (Licenciatura),1,1,1,1,0,0
Educação Física Ciclo Básico,0,0,0,0,1,0
Educação Física Ciclo Básico (Bacharelado/Licenciatura),0,0,0,0,0,1
Enfermagem (Bacharelado),1,1,1,1,1,1
Engenharia Ambiental (Bacharelado),1,1,1,1,0,1
Engenharia Civil (Bacharelado),1,1,1,1,1,1
Engenharia Elétrica (Bacharelado),1,1,1,1,1,1
Engenharia Florestal (Bacharelado),1,1,1,1,0,1
Engenharia Mecatrônica (Bacharelado),0,0,0,0,0,1
Engenharia Mecatrônica – Controle e Automação (Bacharelado),1,1,1,1,1,0
Engenharia Mecânica (Bacharelado),1,1,1,1,1,1
Engenharia Química (Bacharelado),1,1,1,1,1,1
Engenharia de Computação (Bacharelado),1,1,1,1,1,1
Engenharia de Produção (Bacharelado),1,1,1,1,1,1
Engenharia de Redes de Comunicação (Bacharelado),1,1,1,1,1,1
Engenharias – Aeroespacial / Automotiva / Eletrônica / Energia / Software (Bacharelados)**,1,1,1,1,1,1
Estatística (Bacharelado),1,1,1,1,1,1
Farmácia (Bacharelado),1,1,1,1,1,1
Filosofia (Bacharelado/Licenciat ura),0,1,0,0,0,0
Filosofia (Bacharelado/Licenciatura),1,0,1,1,0,1
Filosofia (Licenciatura),1,1,1,1,0,1
Fisioterapia (Bacharelado),1,1,1,1,1,1
Fonoaudiologia (Bacharelado),1,1,1,1,1,1
Física (Bacharelado),1,1,1,1,0,1
Física (Licenciatura),0,0,0,0,0,1
Geofísica (Bacharelado),1,1,1,1,0,1
Geografia (Bacharelado/Licenciat ura),0,1,0,0,0,0
Geografia (Bacharelado/Licenciatura),1,0,1,1,0,1
Geologia (Bacharelado),1,1,1,1,0,1
Gestão Ambiental (Bacharelado),1,1,1,0,0,0
Gestão de Agronegócio (Bacharelado),1,1,1,1,0,1
Gestão de Políticas Públicas (Bacharelado),1,1,1,1,0,1
Gestão do Agronegócio (Bacharelado),1,1,1,1,0,1
História (Bacharelado/Licenciat ura),0,1,0,0,0,0
História (Bacharelado/Licenciatura),1,0,1,1,1,1
História (Licenciatura),1,1,1,1,0,1
Jornalismo (Bacharelado),1,1,1,1,1,1
Letras Português do Brasil como Seg. Língua (Licenciatura),0,0,0,0,0,1
Letras Tradução Espanhol (Bacharelado),0,0,0,0,0,1
Letras Tradução Francês (Bacharelado),0,0,0,0,0,1
Letras Tradução Inglês (Bacharelado),0,0,0,0,0,1
Letras – Português do Brasil como Segunda Língua (Licenciatura),1,1,1,1,0,0
Letras – Tradução Espanhol (Bacharelado),1,1,1,1,0,0
Letras – Tradução – Francês (Bacharelado),1,1,1,1,0,0
Letras – Tradução – Inglês (Bacharelado),1,1,1,1,1,0
Licenciatura em Artes Cênicas,0,0,0,1,0,0
Licenciatura em Artes Cênicas*,1,1,1,0,0,0
Licenciatura em Ciências Biológicas,1,1,1,1,0,0
Licenciatura em Física,1,1,1,1,0,0
Licenciatura em Matemática,1,1,1,1,0,0
Licenciatura em Música*,1,1,0,0,0,0
Licenciatura em Química,1,1,1,1,0,0
Língua Espanhola e Literatura Espanhola e Hispano - Americana (Licenciatura),0,0,0,0,0,1
Língua Espanhola e Literatura Espanhola e Hispano-Americana (Licenciatura),1,1,1,1,0,0
Língua Estrangeira Aplicada – Multilinguismo e Sociedade da Informação (Bacharelado),1,1,1,1,0,0
Língua Francesa (Bacharelado/ Licenciatura),0,0,0,0,0,1
Língua Francesa e Respectiva Literatura (Bacharelado/Licenciat ura),0,1,0,0,0,0
Língua Francesa e Respectiva Literatura (Bacharelado/Licenciatura),1,0,1,1,0,0
Língua Inglesa (Bacharelado/ Licenciatura),0,0,0,0,0,1
Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciat ura),0,1,0,0,0,0
Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciatura),1,0,1,1,1,0
Língua Portuguesa (Bacharelado/ Licenciatura),0,0,0,0,0,1
Língua Portuguesa (Licenciatura),0,0,0,0,0,1
Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciat ura),0,1,0,0,0,0
Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciatura),1,0,1,1,1,0
Língua Portuguesa e Respectiva Literatura (Licenciatura),1,1,1,1,0,0
Língua e Literatura Japonesa (Licenciatura),1,1,1,1,0,1
Línguas Estrangeiras Aplicadas (Bacharelado),0,0,0,0,0,1
Matemática (Bacharelado/ Licenciatura),1,0,1,1,1,0
Matemática (Bacharelado/Licenciat ura),0,1,0,0,0,0
Matemática (Bacharelado/Licenciatura),0,0,0,0,0,1
Matemática (Licenciatura),0,0,0,0,0,1
Medicina (Bacharelado),1,1,1,1,1,1
Medicina Veterinária (Bacharelado),1,1,1,1,1,1
Museologia (Bacharelado),1,1,1,1,0,1
Música (Bacharelado)*,1,0,1,1,0,1
Música (Licenciatura)*,1,1,1,1,0,1
Nutrição (Bacharelado),1,1,1,1,1,1
Odontologia (Bacharelado),1,1,1,1,1,1
Pedagogia (Licenciatura),1,1,1,1,1,1
Psicologia (Bacharelado / Licenciatura / Psicólogo),1,1,1,1,1,0
Psicologia (Bacharelado/Licenciatura/ Psicólogo),0,0,0,0,0,1
Química (Bacharelado),1,1,1,1,1,1
Química (Licenciatura),0,0,0,0,0,1
Química Tecnológica (Bacharelado),1,1,1,1,0,1
Relações Internacionais (Bacharelado),1,1,1,1,1,1
Saúde Coletiva (Bacharelado),1,1,1,1,0,1
Serviço Social (Bacharelado),1,1,1,1,0,1
Teoria Crítica e História da Arte (Bacharelado),0,0,0,0,0,1
"Teoria, Crítica e História da Arte (Bacharelado)",1,1,1,1,0,0
Terapia Ocupacional (Bacharelado),1,1,1,1,1,1
Turismo (Bacharelado),1,1,1,1,0,1

In [26]:
# ============================================================
# ESTATÍSTICAS
# ============================================================

todos = matriz.index[
    matriz.sum(axis=1) == len(DADOS)
]

exclusivos = matriz.index[
    matriz.sum(axis=1) == 1
]

print("=" * 70)
print("ESTATÍSTICAS")
print("=" * 70)

print(f"Cursos distintos        : {len(frequencias)}")
print(f"Presentes em todos      : {len(todos)}")
print(f"Exclusivos de triênio   : {len(exclusivos)}")

======================================================================
ESTATÍSTICAS
======================================================================
Cursos distintos        : 135
Presentes em todos      : 34
Exclusivos de triênio   : 40

In [27]:
# ============================================================
# RELATÓRIOS
# ============================================================

print()

print("CURSOS PRESENTES EM TODOS OS TRIÊNIOS")

print("-" * 70)

for curso in sorted(todos):
    print(curso)

print()

print("CURSOS EXCLUSIVOS")

print("-" * 70)

for curso in sorted(exclusivos):
    print(curso)

print()

print("CURSOS POR TRIÊNIO")

print("-" * 70)

for trienio, df in DADOS.items():

    quantidade = historico.loc[
        historico["Triênio"] == trienio,
        "Curso"
    ].nunique()

    print(f"{trienio}: {quantidade}")

CURSOS PRESENTES EM TODOS OS TRIÊNIOS
----------------------------------------------------------------------
Administração (Bacharelado)
Agronomia (Bacharelado)
Arquitetura e Urbanismo (Bacharelado)
Biotecnologia (Bacharelado)
Ciência Política (Bacharelado)
Ciência da Computação (Bacharelado)
Ciências Contábeis (Bacharelado)
Ciências Econômicas (Bacharelado)
Computação (Licenciatura)
Comunicação Organizacional (Bacharelado)
Comunicação Social – Audiovisual (Bacharelado)
Direito (Bacharelado)
Enfermagem (Bacharelado)
Engenharia Civil (Bacharelado)
Engenharia Elétrica (Bacharelado)
Engenharia Mecânica (Bacharelado)
Engenharia Química (Bacharelado)
Engenharia de Computação (Bacharelado)
Engenharia de Produção (Bacharelado)
Engenharia de Redes de Comunicação (Bacharelado)
Engenharias – Aeroespacial / Automotiva / Eletrônica / Energia / Software (Bacharelados)**
Estatística (Bacharelado)
Farmácia (Bacharelado)
Fisioterapia (Bacharelado)
Fonoaudiologia (Bacharelado)
Jornalismo (Bacharelado)
Medicina (Bacharelado)
Medicina Veterinária (Bacharelado)
Nutrição (Bacharelado)
Odontologia (Bacharelado)
Pedagogia (Licenciatura)
Química (Bacharelado)
Relações Internacionais (Bacharelado)
Terapia Ocupacional (Bacharelado)

CURSOS EXCLUSIVOS
----------------------------------------------------------------------
Arquivologia
Artes Cênicas (Bacharelado)
Artes Cênicas (Licenciatura)
Artes Visuais Licenciatura
Ciências Ambientais
Ciências Biológicas
Ciências Biológicas (Licenciatura)
Ciências Contábeis
Ciências Sociais – Antropologia / Sociologia (Bacharelado/Licenciat ura)
Ciências Sociais – Antropologia/ Sociologia (Bacharelado/Licenciatura)
Comunicação Social – Publicidade e Propaganda (Bacharelado)
Design (Bacharelado)
Design – Programação Visual/Projeto do Produto (Bacharelado)
Educação Física Ciclo Básico
Educação Física Ciclo Básico (Bacharelado/Licenciatura)
Engenharia Mecatrônica (Bacharelado)
Filosofia (Bacharelado/Licenciat ura)
Física (Licenciatura)
Geografia (Bacharelado/Licenciat ura)
História (Bacharelado/Licenciat ura)
Letras Português do Brasil como Seg. Língua (Licenciatura)
Letras Tradução Espanhol (Bacharelado)
Letras Tradução Francês (Bacharelado)
Letras Tradução Inglês (Bacharelado)
Licenciatura em Artes Cênicas
Língua Espanhola e Literatura Espanhola e Hispano - Americana (Licenciatura)
Língua Francesa (Bacharelado/ Licenciatura)
Língua Francesa e Respectiva Literatura (Bacharelado/Licenciat ura)
Língua Inglesa (Bacharelado/ Licenciatura)
Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciat ura)
Língua Portuguesa (Bacharelado/ Licenciatura)
Língua Portuguesa (Licenciatura)
Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciat ura)
Línguas Estrangeiras Aplicadas (Bacharelado)
Matemática (Bacharelado/Licenciat ura)
Matemática (Bacharelado/Licenciatura)
Matemática (Licenciatura)
Psicologia (Bacharelado/Licenciatura/ Psicólogo)
Química (Licenciatura)
Teoria Crítica e História da Arte (Bacharelado)

CURSOS POR TRIÊNIO
----------------------------------------------------------------------
2018-2020: 93
2019-2021: 88
2020-2022: 92
2021-2023: 90
2022-2024: 51
2023-2025: 89

In [28]:
# ============================================================
# EXPORTAÇÃO
# ============================================================

frequencias.to_csv(
    DIR_RELATORIOS / "frequencias_cursos.csv",
    index=False,
    encoding="utf-8-sig"
)

matriz.to_csv(
    DIR_RELATORIOS / "matriz_historica_cursos.csv",
    encoding="utf-8-sig"
)

historico.to_csv(
    DIR_RELATORIOS / "historico_cursos.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Arquivos exportados com sucesso.")

Arquivos exportados com sucesso.

# Relatório para avaliação humana

In [29]:
# ============================================================
# PREPARAÇÃO
# ============================================================

import re


def simplificar_nome(nome):
    """
    Produz uma versão simplificada apenas para comparação.
    Não altera o nome original.
    """

    nome = nome.lower()

    nome = re.sub(r"\(.*?\)", "", nome)

    nome = nome.replace("–", "-")
    nome = nome.replace("—", "-")

    nome = re.sub(r"\s+", " ", nome)

    return nome.strip()


frequencias["Nome simplificado"] = (
    frequencias["Curso"]
    .apply(simplificar_nome)
)

In [30]:
# ============================================================
# AGRUPAMENTOS IMEDIATOS
# ============================================================

agrupamentos = (

    frequencias

    .groupby("Nome simplificado")

    .agg(

        Cursos=("Curso", list),

        Quantidade=("Curso", "size"),

        Ocorrências=("Ocorrências", "sum")

    )

    .reset_index()

)

agrupamentos = agrupamentos[
    agrupamentos["Quantidade"] > 1
]

display(agrupamentos)

,Nome simplificado,Cursos,Quantidade,Ocorrências
3,arquivologia,"[Arquivologia (Bacharelado), Arquivologia]",2,5
4,artes cênicas,"[Artes Cênicas (Licenciatura), Artes Cênicas (Bacharelado)]",2,3
8,artes visuais *,"[Artes Visuais (Bacharelado)*, Artes Visuais (Licenciatura)*]",2,7
18,ciências ambientais,"[Ciências Ambientais (Bacharelado), Ciências Ambientais]",2,5
19,ciências biológicas,"[Ciências Biológicas (Bacharelado), Ciências Biológicas, Ciências Biológicas (Licenciatura)]",3,7
20,ciências contábeis,"[Ciências Contábeis (Bacharelado), Ciências Contábeis]",2,11
23,ciências sociais - antropologia / sociologia,"[Ciências Sociais – Antropologia / Sociologia (Bacharelado/ Licenciatura), Ciências Sociais – Antropologia / Sociologia (Bacharelado/Licenciat ura)]",2,4
28,comunicação social - publicidade e propaganda,"[Comunicação Social - Publicidade e Propaganda (Bacharelado), Comunicação Social – Publicidade e Propaganda (Bacharelado)]",2,6
33,educação física,"[Educação Física (Bacharelado), Educação Física (Licenciatura)]",2,8
34,educação física ciclo básico,"[Educação Física Ciclo Básico, Educação Física Ciclo Básico (Bacharelado/Licenciatura)]",2,2
50,filosofia,"[Filosofia (Licenciatura), Filosofia (Bacharelado/Licenciatura), Filosofia (Bacharelado/Licenciat ura)]",3,10
53,física,"[Física (Bacharelado), Física (Licenciatura)]",2,6
55,geografia,"[Geografia (Bacharelado/Licenciatura), Geografia (Bacharelado/Licenciat ura)]",2,5
61,história,"[História (Bacharelado/Licenciatura), História (Licenciatura), História (Bacharelado/Licenciat ura)]",3,11
83,língua francesa e respectiva literatura,"[Língua Francesa e Respectiva Literatura (Bacharelado/Licenciatura), Língua Francesa e Respectiva Literatura (Bacharelado/Licenciat ura)]",2,4
85,língua inglesa e respectiva literatura,"[Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciatura), Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciat ura)]",2,5
86,língua portuguesa,"[Língua Portuguesa (Bacharelado/ Licenciatura), Língua Portuguesa (Licenciatura)]",2,2
87,língua portuguesa e respectiva literatura,"[Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciatura), Língua Portuguesa e Respectiva Literatura (Licenciatura), Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciat ura)]",3,9
89,matemática,"[Matemática (Bacharelado/ Licenciatura), Matemática (Bacharelado/Licenciat ura), Matemática (Bacharelado/Licenciatura), Matemática (Licenciatura)]",4,7
93,música *,"[Música (Licenciatura)*, Música (Bacharelado)*]",2,9
97,psicologia,"[Psicologia (Bacharelado / Licenciatura / Psicólogo), Psicologia (Bacharelado/Licenciatura/ Psicólogo)]",2,6
98,química,"[Química (Bacharelado), Química (Licenciatura)]",2,7

In [31]:
# ============================================================
# SIMILARIDADE
# ============================================================

!pip -q install rapidfuzz

from rapidfuzz import fuzz

pares = []

nomes = frequencias["Curso"].tolist()

for i, nome1 in enumerate(nomes):

    for nome2 in nomes[i + 1:]:

        score = max(

            fuzz.ratio(
                simplificar_nome(nome1),
                simplificar_nome(nome2)
            ),

            fuzz.token_sort_ratio(
                simplificar_nome(nome1),
                simplificar_nome(nome2)
            ),

            fuzz.token_set_ratio(
                simplificar_nome(nome1),
                simplificar_nome(nome2)
            )

        )

        if score >= 90:

            pares.append({

                "Curso A": nome1,

                "Curso B": nome2,

                "Similaridade": score

            })

pares = (

    pd.DataFrame(pares)

    .sort_values(

        "Similaridade",

        ascending=False

    )

)

display(pares)

,Curso A,Curso B,Similaridade
0,Ciências Contábeis (Bacharelado),Ciências Contábeis,100.000000
1,Ciência da Computação (Bacharelado),Computação (Licenciatura),100.000000
2,Computação (Licenciatura),Engenharia de Computação (Bacharelado),100.000000
3,Engenharia Química (Bacharelado),Química (Bacharelado),100.000000
4,Engenharia Química (Bacharelado),Química (Licenciatura),100.000000
5,Medicina (Bacharelado),Medicina Veterinária (Bacharelado),100.000000
6,Química (Bacharelado),Química Tecnológica (Bacharelado),100.000000
7,Química (Bacharelado),Licenciatura em Química,100.000000
8,Química (Bacharelado),Química (Licenciatura),100.000000
9,Ciências Biológicas (Bacharelado),Licenciatura em Ciências Biológicas,100.000000
10,Ciências Biológicas (Bacharelado),Ciências Biológicas,100.000000
11,Ciências Biológicas (Bacharelado),Ciências Biológicas (Licenciatura),100.000000
12,Comunicação Social - Publicidade e Propaganda (Bacharelado),Comunicação Social – Publicidade e Propaganda (Bacharelado),100.000000
13,Engenharia Mecatrônica – Controle e Automação (Bacharelado),Engenharia Mecatrônica (Bacharelado),100.000000
14,Filosofia (Licenciatura),Filosofia (Bacharelado/Licenciatura),100.000000
15,Filosofia (Licenciatura),Filosofia (Bacharelado/Licenciat ura),100.000000
16,Física (Bacharelado),Educação Física (Bacharelado),100.000000
17,Física (Bacharelado),Educação Física (Licenciatura),100.000000
18,Física (Bacharelado),Licenciatura em Física,100.000000
19,Física (Bacharelado),Educação Física Ciclo Básico,100.000000
20,Física (Bacharelado),Educação Física Ciclo Básico (Bacharelado/Licenciatura),100.000000
21,Física (Bacharelado),Física (Licenciatura),100.000000
23,História (Bacharelado/Licenciatura),História (Licenciatura),100.000000
27,História (Licenciatura),"Teoria, Crítica e História da Arte (Bacharelado)",100.000000
24,História (Bacharelado/Licenciatura),"Teoria, Crítica e História da Arte (Bacharelado)",100.000000
25,História (Bacharelado/Licenciatura),História (Bacharelado/Licenciat ura),100.000000
26,História (Bacharelado/Licenciatura),Teoria Crítica e História da Arte (Bacharelado),100.000000
29,História (Licenciatura),Teoria Crítica e História da Arte (Bacharelado),100.000000
28,História (Licenciatura),História (Bacharelado/Licenciat ura),100.000000
30,Letras – Tradução – Inglês (Bacharelado),Letras Tradução Inglês (Bacharelado),100.000000
31,Música (Licenciatura)*,Música (Bacharelado)*,100.000000
45,Educação Física (Licenciatura),Educação Física Ciclo Básico,100.000000
32,Psicologia (Bacharelado / Licenciatura / Psicólogo),Psicologia (Bacharelado/Licenciatura/ Psicólogo),100.000000
33,Química Tecnológica (Bacharelado),Química (Licenciatura),100.000000
34,Arquivologia (Bacharelado),Arquivologia,100.000000
35,Artes Visuais (Bacharelado)*,Artes Visuais (Licenciatura)*,100.000000
36,Artes Visuais (Bacharelado)*,Artes Visuais (Bacharelado),100.000000
38,Ciências Ambientais (Bacharelado),Ciências Ambientais,100.000000
39,Design – Programação Visual/ Projeto do Produto (Bacharelado),Design (Bacharelado),100.000000
46,Educação Física (Licenciatura),Educação Física Ciclo Básico (Bacharelado/Licenciatura),100.000000
41,Educação Física (Bacharelado),Educação Física (Licenciatura),100.000000
42,Educação Física (Bacharelado),Educação Física Ciclo Básico,100.000000
43,Educação Física (Bacharelado),Educação Física Ciclo Básico (Bacharelado/Licenciatura),100.000000
44,Educação Física (Bacharelado),Física (Licenciatura),100.000000
49,Geografia (Bacharelado/Licenciatura),Geografia (Bacharelado/Licenciat ura),100.000000
48,Filosofia (Bacharelado/Licenciatura),Filosofia (Bacharelado/Licenciat ura),100.000000
47,Educação Física (Licenciatura),Física (Licenciatura),100.000000
109,Matemática (Bacharelado/Licenciat ura),Matemática (Licenciatura),100.000000
105,Língua Portuguesa (Bacharelado/ Licenciatura),Língua Portuguesa (Licenciatura),100.000000
106,Língua Portuguesa (Bacharelado/ Licenciatura),Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000
51,Letras – Tradução Espanhol (Bacharelado),Letras Tradução Espanhol (Bacharelado),100.000000
53,Licenciatura em Ciências Biológicas,Ciências Biológicas,100.000000
52,Letras – Tradução – Francês (Bacharelado),Letras Tradução Francês (Bacharelado),100.000000
54,Licenciatura em Ciências Biológicas,Ciências Biológicas (Licenciatura),100.000000
55,Licenciatura em Física,Física (Licenciatura),100.000000
59,Licenciatura em Matemática,Matemática (Licenciatura),100.000000
56,Licenciatura em Matemática,Matemática (Bacharelado/ Licenciatura),100.000000
57,Licenciatura em Matemática,Matemática (Bacharelado/Licenciat ura),100.000000
58,Licenciatura em Matemática,Matemática (Bacharelado/Licenciatura),100.000000
60,Licenciatura em Química,Química (Licenciatura),100.000000
66,Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Portuguesa e Respectiva Literatura (Licenciatura),100.000000
65,Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000
64,Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Inglesa (Bacharelado/ Licenciatura),100.000000
75,Matemática (Bacharelado/ Licenciatura),Matemática (Licenciatura),100.000000
72,Língua Portuguesa e Respectiva Literatura (Licenciatura),Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000
73,Matemática (Bacharelado/ Licenciatura),Matemática (Bacharelado/Licenciat ura),100.000000
67,Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Portuguesa (Bacharelado/ Licenciatura),100.000000
69,Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000
68,Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Portuguesa (Licenciatura),100.000000
70,Língua Portuguesa e Respectiva Literatura (Licenciatura),Língua Portuguesa (Bacharelado/ Licenciatura),100.000000
71,Língua Portuguesa e Respectiva Literatura (Licenciatura),Língua Portuguesa (Licenciatura),100.000000
76,"Teoria, Crítica e História da Arte (Bacharelado)",História (Bacharelado/Licenciat ura),100.000000
74,Matemática (Bacharelado/ Licenciatura),Matemática (Bacharelado/Licenciatura),100.000000
85,Língua Francesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Francesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000
84,Língua Francesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Francesa (Bacharelado/ Licenciatura),100.000000
82,Ciências Sociais – Antropologia / Sociologia (Bacharelado/ Licenciatura),Ciências Sociais – Antropologia / Sociologia (Bacharelado/Licenciat ura),100.000000
81,Artes Cênicas - Interpretação Teatral (Bacharelado) *,Artes Cênicas (Bacharelado),100.000000
80,Artes Cênicas - Interpretação Teatral (Bacharelado) *,Artes Cênicas (Licenciatura),100.000000
79,Artes Cênicas - Interpretação Teatral (Bacharelado) *,Artes Cênicas - Interpretação Teatral (Bacharelado),100.000000
110,Matemática (Bacharelado/Licenciatura),Matemática (Licenciatura),100.000000
108,Matemática (Bacharelado/Licenciat ura),Matemática (Bacharelado/Licenciatura),100.000000
107,Língua Portuguesa (Licenciatura),Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000
99,Educação Física Ciclo Básico,Física (Licenciatura),100.000000
101,História (Bacharelado/Licenciat ura),Teoria Crítica e História da Arte (Bacharelado),100.000000
100,Educação Física Ciclo Básico (Bacharelado/Licenciatura),Física (Licenciatura),100.000000
89,Artes Cênicas - Interpretação Teatral (Bacharelado),Artes Cênicas (Licenciatura),100.000000
87,Artes Visuais (Licenciatura)*,Artes Visuais (Bacharelado),100.000000
93,Artes Cênicas (Licenciatura),Artes Cênicas (Bacharelado),100.000000
92,Artes Cênicas (Licenciatura),Licenciatura em Artes Cênicas,100.000000
90,Artes Cênicas - Interpretação Teatral (Bacharelado),Artes Cênicas (Bacharelado),100.000000
91,Artes Visuais (Bacharelado),Artes Visuais Licenciatura,100.000000
94,Licenciatura em Artes Cênicas,Artes Cênicas (Bacharelado),100.000000
98,Educação Física Ciclo Básico,Educação Física Ciclo Básico (Bacharelado/Licenciatura),100.000000
97,Design (Bacharelado),Design – Programação Visual/Projeto do Produto (Bacharelado),100.000000
95,Ciências Biológicas,Ciências Biológicas (Licenciatura),100.000000
102,Língua Francesa (Bacharelado/ Licenciatura),Língua Francesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000
104,Língua Inglesa (Bacharelado/ Licenciatura),Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000
40,Design – Programação Visual/ Projeto do Produto (Bacharelado),Design – Programação Visual/Projeto do Produto (Bacharelado),98.924731
83,Ciências Sociais – Antropologia / Sociologia (Bacharelado/ Licenciatura),Ciências Sociais – Antropologia/ Sociologia (Bacharelado/Licenciatura),98.850575
96,Ciências Sociais – Antropologia / Sociologia (Bacharelado/Licenciat ura),Ciências Sociais – Antropologia/ Sociologia (Bacharelado/Licenciatura),98.850575
77,"Teoria, Crítica e História da Arte (Bacharelado)",Teoria Crítica e História da Arte (Bacharelado),98.507463
61,Língua Espanhola e Literatura Espanhola e Hispano-Americana (Licenciatura),Língua Espanhola e Literatura Espanhola e Hispano - Americana (Licenciatura),98.333333
78,Licenciatura em Artes Cênicas*,Licenciatura em Artes Cênicas,98.305085
22,Gestão de Agronegócio (Bacharelado),Gestão do Agronegócio (Bacharelado),95.238095
50,Letras – Português do Brasil como Segunda Língua (Licenciatura),Letras Português do Brasil como Seg. Língua (Licenciatura),93.827160
37,Artes Visuais (Bacharelado)*,Artes Visuais Licenciatura,92.857143
88,Artes Visuais (Licenciatura)*,Artes Visuais Licenciatura,92.857143
63,Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Francesa e Respectiva Literatura (Bacharelado/Licenciat ura),90.909091
62,Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Francesa e Respectiva Literatura (Bacharelado/Licenciatura),90.909091
86,Língua Francesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciat ura),90.909091
103,Língua Francesa e Respectiva Literatura (Bacharelado/Licenciat ura),Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciat ura),90.909091

In [32]:
# ============================================================
# CANDIDATOS
# ============================================================

def trienios(curso):

    return sorted(

        historico.loc[

            historico["Curso"] == curso,

            "Triênio"

        ].unique()

    )


candidatos = []

for _, linha in pares.iterrows():

    a = linha["Curso A"]
    b = linha["Curso B"]

    candidatos.append({

        "Curso A": a,

        "Curso B": b,

        "Similaridade": linha["Similaridade"],

        "Triênios A": ", ".join(trienios(a)),

        "Triênios B": ", ".join(trienios(b)),

        "Ocorrências A": int(

            frequencias.loc[
                frequencias["Curso"] == a,
                "Ocorrências"
            ].iloc[0]
        ),

        "Ocorrências B": int(

            frequencias.loc[
                frequencias["Curso"] == b,
                "Ocorrências"
            ].iloc[0]
        )

    })

candidatos = pd.DataFrame(candidatos)

display(candidatos)

,Curso A,Curso B,Similaridade,Triênios A,Triênios B,Ocorrências A,Ocorrências B
0,Ciências Contábeis (Bacharelado),Ciências Contábeis,100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025",2019-2021,10,1
1,Ciência da Computação (Bacharelado),Computação (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025",6,6
2,Computação (Licenciatura),Engenharia de Computação (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025",6,6
3,Engenharia Química (Bacharelado),Química (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025",6,6
4,Engenharia Química (Bacharelado),Química (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025",2023-2025,6,1
5,Medicina (Bacharelado),Medicina Veterinária (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025",6,6
6,Química (Bacharelado),Química Tecnológica (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025",6,5
7,Química (Bacharelado),Licenciatura em Química,100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023",6,4
8,Química (Bacharelado),Química (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024, 2023-2025",2023-2025,6,1
9,Ciências Biológicas (Bacharelado),Licenciatura em Ciências Biológicas,100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023",5,4
10,Ciências Biológicas (Bacharelado),Ciências Biológicas,100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024, 2023-2025",2019-2021,5,1
11,Ciências Biológicas (Bacharelado),Ciências Biológicas (Licenciatura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024, 2023-2025",2023-2025,5,1
12,Comunicação Social - Publicidade e Propaganda (Bacharelado),Comunicação Social – Publicidade e Propaganda (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024",2023-2025,5,1
13,Engenharia Mecatrônica – Controle e Automação (Bacharelado),Engenharia Mecatrônica (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024",2023-2025,5,1
14,Filosofia (Licenciatura),Filosofia (Bacharelado/Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025","2018-2020, 2020-2022, 2021-2023, 2023-2025",5,4
15,Filosofia (Licenciatura),Filosofia (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025",2019-2021,5,1
16,Física (Bacharelado),Educação Física (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023",5,4
17,Física (Bacharelado),Educação Física (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023",5,4
18,Física (Bacharelado),Licenciatura em Física,100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023",5,4
19,Física (Bacharelado),Educação Física Ciclo Básico,100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025",2022-2024,5,1
20,Física (Bacharelado),Educação Física Ciclo Básico (Bacharelado/Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025",2023-2025,5,1
21,Física (Bacharelado),Física (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025",2023-2025,5,1
22,História (Bacharelado/Licenciatura),História (Licenciatura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025",5,5
23,História (Licenciatura),"Teoria, Crítica e História da Arte (Bacharelado)",100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023",5,4
24,História (Bacharelado/Licenciatura),"Teoria, Crítica e História da Arte (Bacharelado)",100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023",5,4
25,História (Bacharelado/Licenciatura),História (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024, 2023-2025",2019-2021,5,1
26,História (Bacharelado/Licenciatura),Teoria Crítica e História da Arte (Bacharelado),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024, 2023-2025",2023-2025,5,1
27,História (Licenciatura),Teoria Crítica e História da Arte (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025",2023-2025,5,1
28,História (Licenciatura),História (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025",2019-2021,5,1
29,Letras – Tradução – Inglês (Bacharelado),Letras Tradução Inglês (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024",2023-2025,5,1
30,Música (Licenciatura)*,Música (Bacharelado)*,100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025","2018-2020, 2020-2022, 2021-2023, 2023-2025",5,4
31,Educação Física (Licenciatura),Educação Física Ciclo Básico,100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2022-2024,4,1
32,Psicologia (Bacharelado / Licenciatura / Psicólogo),Psicologia (Bacharelado/Licenciatura/ Psicólogo),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2022-2024",2023-2025,5,1
33,Química Tecnológica (Bacharelado),Química (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025",2023-2025,5,1
34,Arquivologia (Bacharelado),Arquivologia,100.000000,"2018-2020, 2020-2022, 2021-2023, 2023-2025",2019-2021,4,1
35,Artes Visuais (Bacharelado)*,Artes Visuais (Licenciatura)*,100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023","2018-2020, 2020-2022",4,3
36,Artes Visuais (Bacharelado)*,Artes Visuais (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023","2022-2024, 2023-2025",4,2
37,Ciências Ambientais (Bacharelado),Ciências Ambientais,100.000000,"2018-2020, 2020-2022, 2021-2023, 2023-2025",2019-2021,4,1
38,Design – Programação Visual/ Projeto do Produto (Bacharelado),Design (Bacharelado),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024",2023-2025,4,1
39,Educação Física (Licenciatura),Educação Física Ciclo Básico (Bacharelado/Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
40,Educação Física (Bacharelado),Educação Física (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023","2018-2020, 2019-2021, 2020-2022, 2021-2023",4,4
41,Educação Física (Bacharelado),Educação Física Ciclo Básico,100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2022-2024,4,1
42,Educação Física (Bacharelado),Educação Física Ciclo Básico (Bacharelado/Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
43,Educação Física (Bacharelado),Física (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
44,Geografia (Bacharelado/Licenciatura),Geografia (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2023-2025",2019-2021,4,1
45,Filosofia (Bacharelado/Licenciatura),Filosofia (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2023-2025",2019-2021,4,1
46,Educação Física (Licenciatura),Física (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
47,Matemática (Bacharelado/Licenciat ura),Matemática (Licenciatura),100.000000,2019-2021,2023-2025,1,1
48,Língua Portuguesa (Bacharelado/ Licenciatura),Língua Portuguesa (Licenciatura),100.000000,2023-2025,2023-2025,1,1
49,Língua Portuguesa (Bacharelado/ Licenciatura),Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000,2023-2025,2019-2021,1,1
50,Letras – Tradução Espanhol (Bacharelado),Letras Tradução Espanhol (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
51,Licenciatura em Ciências Biológicas,Ciências Biológicas,100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2019-2021,4,1
52,Letras – Tradução – Francês (Bacharelado),Letras Tradução Francês (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
53,Licenciatura em Ciências Biológicas,Ciências Biológicas (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
54,Licenciatura em Física,Física (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
55,Licenciatura em Matemática,Matemática (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
56,Licenciatura em Matemática,Matemática (Bacharelado/ Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023","2018-2020, 2020-2022, 2021-2023, 2022-2024",4,4
57,Licenciatura em Matemática,Matemática (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2019-2021,4,1
58,Licenciatura em Matemática,Matemática (Bacharelado/Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
59,Licenciatura em Química,Química (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
60,Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Portuguesa e Respectiva Literatura (Licenciatura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024","2018-2020, 2019-2021, 2020-2022, 2021-2023",4,4
61,Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024",2019-2021,4,1
62,Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Inglesa (Bacharelado/ Licenciatura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024",2023-2025,4,1
63,Matemática (Bacharelado/ Licenciatura),Matemática (Licenciatura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024",2023-2025,4,1
64,Língua Portuguesa e Respectiva Literatura (Licenciatura),Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2019-2021,4,1
65,Matemática (Bacharelado/ Licenciatura),Matemática (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024",2019-2021,4,1
66,Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Portuguesa (Bacharelado/ Licenciatura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024",2023-2025,4,1
67,Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024",2019-2021,4,1
68,Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Portuguesa (Licenciatura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024",2023-2025,4,1
69,Língua Portuguesa e Respectiva Literatura (Licenciatura),Língua Portuguesa (Bacharelado/ Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
70,Língua Portuguesa e Respectiva Literatura (Licenciatura),Língua Portuguesa (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
71,"Teoria, Crítica e História da Arte (Bacharelado)",História (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2019-2021,4,1
72,Matemática (Bacharelado/ Licenciatura),Matemática (Bacharelado/Licenciatura),100.000000,"2018-2020, 2020-2022, 2021-2023, 2022-2024",2023-2025,4,1
73,Língua Francesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Francesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2020-2022, 2021-2023",2019-2021,3,1
74,Língua Francesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Francesa (Bacharelado/ Licenciatura),100.000000,"2018-2020, 2020-2022, 2021-2023",2023-2025,3,1
75,Ciências Sociais – Antropologia / Sociologia (Bacharelado/ Licenciatura),Ciências Sociais – Antropologia / Sociologia (Bacharelado/Licenciat ura),100.000000,"2018-2020, 2020-2022, 2021-2023",2019-2021,3,1
76,Artes Cênicas - Interpretação Teatral (Bacharelado) *,Artes Cênicas (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022",2023-2025,3,1
77,Artes Cênicas - Interpretação Teatral (Bacharelado) *,Artes Cênicas (Licenciatura),100.000000,"2018-2020, 2019-2021, 2020-2022",2023-2025,3,2
78,Artes Cênicas - Interpretação Teatral (Bacharelado) *,Artes Cênicas - Interpretação Teatral (Bacharelado),100.000000,"2018-2020, 2019-2021, 2020-2022","2021-2023, 2022-2024",3,2
79,Matemática (Bacharelado/Licenciatura),Matemática (Licenciatura),100.000000,2023-2025,2023-2025,1,1
80,Matemática (Bacharelado/Licenciat ura),Matemática (Bacharelado/Licenciatura),100.000000,2019-2021,2023-2025,1,1
81,Língua Portuguesa (Licenciatura),Língua Portuguesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000,2023-2025,2019-2021,1,1
82,Educação Física Ciclo Básico,Física (Licenciatura),100.000000,2022-2024,2023-2025,1,1
83,História (Bacharelado/Licenciat ura),Teoria Crítica e História da Arte (Bacharelado),100.000000,2019-2021,2023-2025,1,1
84,Educação Física Ciclo Básico (Bacharelado/Licenciatura),Física (Licenciatura),100.000000,2023-2025,2023-2025,1,1
85,Artes Cênicas - Interpretação Teatral (Bacharelado),Artes Cênicas (Licenciatura),100.000000,"2021-2023, 2022-2024",2023-2025,2,2
86,Artes Visuais (Licenciatura)*,Artes Visuais (Bacharelado),100.000000,"2018-2020, 2020-2022","2022-2024, 2023-2025",3,2
87,Artes Cênicas (Licenciatura),Artes Cênicas (Bacharelado),100.000000,2023-2025,2023-2025,2,1
88,Artes Cênicas (Licenciatura),Licenciatura em Artes Cênicas,100.000000,2023-2025,2021-2023,2,2
89,Artes Cênicas - Interpretação Teatral (Bacharelado),Artes Cênicas (Bacharelado),100.000000,"2021-2023, 2022-2024",2023-2025,2,1
90,Artes Visuais (Bacharelado),Artes Visuais Licenciatura,100.000000,"2022-2024, 2023-2025",2022-2024,2,1
91,Licenciatura em Artes Cênicas,Artes Cênicas (Bacharelado),100.000000,2021-2023,2023-2025,2,1
92,Educação Física Ciclo Básico,Educação Física Ciclo Básico (Bacharelado/Licenciatura),100.000000,2022-2024,2023-2025,1,1
93,Design (Bacharelado),Design – Programação Visual/Projeto do Produto (Bacharelado),100.000000,2023-2025,2019-2021,1,1
94,Ciências Biológicas,Ciências Biológicas (Licenciatura),100.000000,2019-2021,2023-2025,1,1
95,Língua Francesa (Bacharelado/ Licenciatura),Língua Francesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000,2023-2025,2019-2021,1,1
96,Língua Inglesa (Bacharelado/ Licenciatura),Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciat ura),100.000000,2023-2025,2019-2021,1,1
97,Design – Programação Visual/ Projeto do Produto (Bacharelado),Design – Programação Visual/Projeto do Produto (Bacharelado),98.924731,"2018-2020, 2020-2022, 2021-2023, 2022-2024",2019-2021,4,1
98,Ciências Sociais – Antropologia / Sociologia (Bacharelado/ Licenciatura),Ciências Sociais – Antropologia/ Sociologia (Bacharelado/Licenciatura),98.850575,"2018-2020, 2020-2022, 2021-2023",2023-2025,3,1
99,Ciências Sociais – Antropologia / Sociologia (Bacharelado/Licenciat ura),Ciências Sociais – Antropologia/ Sociologia (Bacharelado/Licenciatura),98.850575,2019-2021,2023-2025,1,1
100,"Teoria, Crítica e História da Arte (Bacharelado)",Teoria Crítica e História da Arte (Bacharelado),98.507463,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
101,Língua Espanhola e Literatura Espanhola e Hispano-Americana (Licenciatura),Língua Espanhola e Literatura Espanhola e Hispano - Americana (Licenciatura),98.333333,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
102,Licenciatura em Artes Cênicas*,Licenciatura em Artes Cênicas,98.305085,"2018-2020, 2019-2021, 2020-2022",2021-2023,5,2
103,Gestão de Agronegócio (Bacharelado),Gestão do Agronegócio (Bacharelado),95.238095,"2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025","2018-2020, 2019-2021, 2020-2022, 2021-2023, 2023-2025",5,5
104,Letras – Português do Brasil como Segunda Língua (Licenciatura),Letras Português do Brasil como Seg. Língua (Licenciatura),93.827160,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2023-2025,4,1
105,Artes Visuais (Bacharelado)*,Artes Visuais Licenciatura,92.857143,"2018-2020, 2019-2021, 2020-2022, 2021-2023",2022-2024,4,1
106,Artes Visuais (Licenciatura)*,Artes Visuais Licenciatura,92.857143,"2018-2020, 2020-2022",2022-2024,3,1
107,Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Francesa e Respectiva Literatura (Bacharelado/Licenciat ura),90.909091,"2018-2020, 2020-2022, 2021-2023, 2022-2024",2019-2021,4,1
108,Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Francesa e Respectiva Literatura (Bacharelado/Licenciatura),90.909091,"2018-2020, 2020-2022, 2021-2023, 2022-2024","2018-2020, 2020-2022, 2021-2023",4,3
109,Língua Francesa e Respectiva Literatura (Bacharelado/Licenciatura),Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciat ura),90.909091,"2018-2020, 2020-2022, 2021-2023",2019-2021,3,1
110,Língua Francesa e Respectiva Literatura (Bacharelado/Licenciat ura),Língua Inglesa e Respectiva Literatura (Bacharelado/Licenciat ura),90.909091,2019-2021,2019-2021,1,1

In [33]:
# ============================================================
# EXPORTAÇÃO
# ============================================================

candidatos.to_csv(
    DIR_RELATORIOS / "candidatos_normalizacao.csv",
    index=False,
    encoding="utf-8-sig"
)

agrupamentos.to_csv(
    DIR_RELATORIOS / "agrupamentos_imediatos.csv",
    index=False,
    encoding="utf-8-sig"
)

print("=" * 70)
print("RELATÓRIOS GERADOS")
print("=" * 70)

print("✓ candidatos_normalizacao.csv")
print("✓ agrupamentos_imediatos.csv")

======================================================================
RELATÓRIOS GERADOS
======================================================================
✓ candidatos_normalizacao.csv
✓ agrupamentos_imediatos.csv

In [34]:
# ============================================================
# PLANILHA DE REVISÃO
# ============================================================

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

wb = Workbook()
ws = wb.active
ws.title = "Cursos"

cabecalho = [
    "Curso histórico",
    "Ocorrências",
    "Nº triênios",
    "Lista de triênios",
    "Nome simplificado",
    "Curso canônico",
    "Ação",
    "Observação",
]

for coluna, texto in enumerate(cabecalho, start=1):

    celula = ws.cell(row=1, column=coluna)

    celula.value = texto
    celula.font = Font(bold=True)
    celula.fill = PatternFill(
        fill_type="solid",
        fgColor="D9EAD3"
    )

for _, linha in frequencias.iterrows():

    ws.append([

        linha["Curso"],

        int(linha["Ocorrências"]),

        int(linha["Triênios"]),

        linha["Lista_de_triênios"],

        linha["Nome simplificado"],

        "",

        "",

        ""

    ])

# Ajuste simples da largura das colunas

larguras = {
    "A": 55,
    "B": 12,
    "C": 12,
    "D": 30,
    "E": 55,
    "F": 55,
    "G": 18,
    "H": 40,
}

for coluna, largura in larguras.items():
    ws.column_dimensions[coluna].width = largura

arquivo = DIR_CATALOGOS / "revisao_cursos.xlsx"

wb.save(arquivo)

print("=" * 70)
print("PLANILHA DE REVISÃO GERADA")
print("=" * 70)
print(arquivo)

======================================================================
PLANILHA DE REVISÃO GERADA
======================================================================
/content/drive/MyDrive/Dados/PAS/catalogos/revisao_cursos.xlsx